version: "3"
services:
    api1:
        image: api1
        container_name: api1
        build:
            context: ./api1
            dockerfile: Dockerfile
        networks:
            api:
                aliases:
                    - api1
        ports:
            - "5001:80"
        depends_on:
                - api2
    api2:
        image: api2
        container_name: api2
        build:
            context: ./api2
            dockerfile: Dockerfile
        networks:
            api:
                aliases: 
                    - api2
        ports:
            - "5002:80"        
networks:
    api:
        name: api
        driver: bridge
